// Generated by Unloop
// Smart Home Hub

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_lights_off_clicked(|| {
        println!("lights_off clicked");
    });
    
    app.on_away_mode_clicked(|| {
        println!("away_mode clicked");
    });
    
    app.on_goodnight_scene_clicked(|| {
        println!("goodnight_scene clicked");
    });
    

    
    app.run()
}
